search_depth = 10
need_check_chart = true
need_check_script = true
thread_handels = 4
command_history = 30
music_volume = 1.0
click_sound_volume = 1.0

[enabled_script]

[log_remain]
secs = 43200
nanos = 0

[offset]
time = -656.35595703125
